# 日志配置管理示例配置
plugin:
  store:
    type: SQLITE  # 存储类型：MEMORY、SQLITE
  sqlite:
    database-path: plugin.db  # SQLite数据库文件路径

# 日志配置
logging:
  level:
    com.chua.starter.plugin: DEBUG
    com.chua.starter.plugin.service.LoggerConfigService: DEBUG
    com.chua.starter.plugin.controller.LoggerConfigController: DEBUG

# Spring Boot配置
spring:
  application:
    name: logger-config-demo

# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /

# 管理端点配置（用于模拟actuator）
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    loggers:
      enabled: true
