# XSS防护配置示例
plugin:
  store:
    type: SQLITE  # 存储类型：MEMORY、SQLITE
  sqlite:
    database-path: plugin.db  # SQLite数据库文件路径

# 日志配置
logging:
  level:
    com.chua.starter.plugin: DEBUG
    com.chua.starter.plugin.filter: DEBUG
    com.chua.starter.plugin.service: DEBUG

# Spring Boot配置
spring:
  application:
    name: xss-protection-demo
  
# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /
