# 设备数据上报配置示例
plugin:
  report:
    client:
      # 是否启用设备数据上报
      enable: true
      
      # 上报服务器地址
      address: "http://localhost:8080"
      
      # 接收协议
      receivable-protocol: "http"
      
      # 接收端口
      receivable-port: 8080
      
      # 推送间隔时间（秒）
      push-interval: 30
      
      # 初始延迟时间（秒）
      initial-delay: 10
      
      # 连接超时时间（毫秒）
      connect-timeout: 5000
      
      # 读取超时时间（毫秒）
      read-timeout: 10000
      
      # 重试次数
      retry-count: 3
      
      # 设备标识（可选，不设置会自动生成）
      device-id: "device-001"
      
      # 设备名称（可选，不设置会使用主机名）
      device-name: "测试设备"

# 日志配置
logging:
  level:
    com.chua.report.client.starter: DEBUG
    com.chua.oshi.support: DEBUG
