SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS `soft_repository` (
  `soft_repository_id` INT NOT NULL AUTO_INCREMENT COMMENT '仓库ID',
  `repository_name` VARCHAR(255) DEFAULT NULL COMMENT '仓库名称',
  `repository_code` VARCHAR(255) DEFAULT NULL COMMENT '仓库编码',
  `repository_type` VARCHAR(64) DEFAULT NULL COMMENT '仓库类型',
  `repository_url` VARCHAR(1024) DEFAULT NULL COMMENT '仓库地址',
  `local_directory` VARCHAR(1024) DEFAULT NULL COMMENT '本地仓库目录',
  `auth_type` VARCHAR(64) DEFAULT NULL COMMENT '认证类型',
  `username` VARCHAR(255) DEFAULT NULL COMMENT '用户名',
  `password` VARCHAR(2048) DEFAULT NULL COMMENT '密码密文',
  `token` VARCHAR(4096) DEFAULT NULL COMMENT '令牌密文',
  `sync_cron` VARCHAR(255) DEFAULT NULL COMMENT '同步表达式',
  `sync_config` TEXT DEFAULT NULL COMMENT '同步配置',
  `source_configs_json` LONGTEXT DEFAULT NULL COMMENT '额外同步源JSON',
  `enabled` TINYINT(1) DEFAULT 1 COMMENT '是否启用',
  `last_sync_time` DATETIME DEFAULT NULL COMMENT '最后同步时间',
  `last_sync_status` VARCHAR(64) DEFAULT NULL COMMENT '最后同步状态',
  `last_sync_message` VARCHAR(1024) DEFAULT NULL COMMENT '最后同步说明',
  `create_name` VARCHAR(255) DEFAULT NULL,
  `create_by` INT DEFAULT NULL,
  `create_time` DATETIME DEFAULT NULL,
  `update_time` DATETIME DEFAULT NULL,
  `update_name` VARCHAR(255) DEFAULT NULL,
  `update_by` INT DEFAULT NULL,
  PRIMARY KEY (`soft_repository_id`),
  UNIQUE KEY `uk_soft_repository_code` (`repository_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='软件仓库';

CREATE TABLE IF NOT EXISTS `soft_repository_source` (
  `soft_repository_source_id` INT NOT NULL AUTO_INCREMENT COMMENT '来源ID',
  `soft_repository_id` INT NOT NULL COMMENT '仓库ID',
  `source_name` VARCHAR(255) DEFAULT NULL COMMENT '来源名称',
  `source_kind` VARCHAR(64) DEFAULT NULL COMMENT '来源分类',
  `source_type` VARCHAR(64) DEFAULT NULL COMMENT '来源类型',
  `source_url` VARCHAR(1024) DEFAULT NULL COMMENT '来源地址',
  `local_directory` VARCHAR(1024) DEFAULT NULL COMMENT '本地目录',
  `auth_type` VARCHAR(64) DEFAULT NULL COMMENT '认证类型',
  `username` VARCHAR(255) DEFAULT NULL COMMENT '用户名',
  `password` VARCHAR(2048) DEFAULT NULL COMMENT '密码密文',
  `token` VARCHAR(4096) DEFAULT NULL COMMENT '令牌密文',
  `enabled` TINYINT(1) DEFAULT 1 COMMENT '是否启用',
  `sort_order` INT DEFAULT 10 COMMENT '排序',
  `source_config` TEXT DEFAULT NULL COMMENT '来源附加配置',
  `create_name` VARCHAR(255) DEFAULT NULL,
  `create_by` INT DEFAULT NULL,
  `create_time` DATETIME DEFAULT NULL,
  `update_time` DATETIME DEFAULT NULL,
  `update_name` VARCHAR(255) DEFAULT NULL,
  `update_by` INT DEFAULT NULL,
  PRIMARY KEY (`soft_repository_source_id`),
  KEY `idx_soft_repo_source_repository` (`soft_repository_id`),
  KEY `idx_soft_repo_source_kind_enabled` (`soft_repository_id`, `source_kind`, `enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='仓库来源子表';

CREATE TABLE IF NOT EXISTS `soft_package` (
  `soft_package_id` INT NOT NULL AUTO_INCREMENT COMMENT '软件ID',
  `soft_repository_id` INT DEFAULT NULL COMMENT '仓库ID',
  `soft_package_profile_id` INT DEFAULT NULL COMMENT '软件画像ID',
  `package_code` VARCHAR(255) DEFAULT NULL COMMENT '软件编码',
  `profile_code` VARCHAR(255) DEFAULT NULL COMMENT '软件画像编码',
  `package_name` VARCHAR(255) DEFAULT NULL COMMENT '软件名称',
  `package_category` VARCHAR(255) DEFAULT NULL COMMENT '分类',
  `os_type` VARCHAR(64) DEFAULT NULL COMMENT '操作系统',
  `architecture` VARCHAR(64) DEFAULT NULL COMMENT '架构',
  `description` TEXT DEFAULT NULL COMMENT '描述',
  `icon_url` VARCHAR(1024) DEFAULT NULL COMMENT '图标',
  `create_name` VARCHAR(255) DEFAULT NULL,
  `create_by` INT DEFAULT NULL,
  `create_time` DATETIME DEFAULT NULL,
  `update_time` DATETIME DEFAULT NULL,
  `update_name` VARCHAR(255) DEFAULT NULL,
  `update_by` INT DEFAULT NULL,
  PRIMARY KEY (`soft_package_id`),
  UNIQUE KEY `uk_soft_package_identity` (`soft_repository_id`, `package_code`),
  KEY `idx_soft_package_repository_id` (`soft_repository_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='软件主档';

CREATE TABLE IF NOT EXISTS `soft_package_profile` (
  `soft_package_profile_id` INT NOT NULL AUTO_INCREMENT COMMENT '软件画像ID',
  `profile_code` VARCHAR(255) DEFAULT NULL COMMENT '画像编码',
  `profile_name` VARCHAR(255) DEFAULT NULL COMMENT '画像名称',
  `package_category` VARCHAR(255) DEFAULT NULL COMMENT '分类',
  `description` VARCHAR(1024) DEFAULT NULL COMMENT '描述',
  `builtin` TINYINT(1) DEFAULT 1 COMMENT '是否内置',
  `enabled` TINYINT(1) DEFAULT 1 COMMENT '是否启用',
  `metadata_json` TEXT DEFAULT NULL COMMENT '扩展元数据',
  `create_name` VARCHAR(255) DEFAULT NULL,
  `create_by` INT DEFAULT NULL,
  `create_time` DATETIME DEFAULT NULL,
  `update_time` DATETIME DEFAULT NULL,
  `update_name` VARCHAR(255) DEFAULT NULL,
  `update_by` INT DEFAULT NULL,
  PRIMARY KEY (`soft_package_profile_id`),
  UNIQUE KEY `uk_soft_package_profile_code` (`profile_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='软件画像';

CREATE TABLE IF NOT EXISTS `soft_package_profile_field` (
  `soft_package_profile_field_id` INT NOT NULL AUTO_INCREMENT COMMENT '画像字段ID',
  `soft_package_profile_id` INT DEFAULT NULL COMMENT '画像ID',
  `field_key` VARCHAR(255) DEFAULT NULL COMMENT '字段编码',
  `field_label` VARCHAR(255) DEFAULT NULL COMMENT '字段名称',
  `field_scope` VARCHAR(64) DEFAULT NULL COMMENT '字段作用域',
  `component_type` VARCHAR(64) DEFAULT NULL COMMENT '组件类型',
  `group_name` VARCHAR(255) DEFAULT NULL COMMENT '分组名称',
  `field_description` VARCHAR(1024) DEFAULT NULL COMMENT '字段说明',
  `sort_order` INT DEFAULT NULL COMMENT '排序',
  `required_flag` TINYINT(1) DEFAULT 0 COMMENT '是否必填',
  `default_value` TEXT DEFAULT NULL COMMENT '默认值',
  `options_json` TEXT DEFAULT NULL COMMENT '选项JSON',
  `validation_json` TEXT DEFAULT NULL COMMENT '校验JSON',
  `condition_json` TEXT DEFAULT NULL COMMENT '显示条件JSON',
  `target_path` VARCHAR(255) DEFAULT NULL COMMENT '渲染目标',
  `metadata_json` TEXT DEFAULT NULL COMMENT '扩展元数据',
  `create_name` VARCHAR(255) DEFAULT NULL,
  `create_by` INT DEFAULT NULL,
  `create_time` DATETIME DEFAULT NULL,
  `update_time` DATETIME DEFAULT NULL,
  `update_name` VARCHAR(255) DEFAULT NULL,
  `update_by` INT DEFAULT NULL,
  PRIMARY KEY (`soft_package_profile_field_id`),
  KEY `idx_soft_profile_field_profile_id` (`soft_package_profile_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='软件画像字段';

CREATE TABLE IF NOT EXISTS `soft_package_profile_template` (
  `soft_package_profile_template_id` INT NOT NULL AUTO_INCREMENT COMMENT '画像模板ID',
  `soft_package_profile_id` INT DEFAULT NULL COMMENT '画像ID',
  `template_scope` VARCHAR(64) DEFAULT NULL COMMENT '模板作用域',
  `template_code` VARCHAR(255) DEFAULT NULL COMMENT '模板编码',
  `template_name` VARCHAR(255) DEFAULT NULL COMMENT '模板名称',
  `template_path` VARCHAR(1024) DEFAULT NULL COMMENT '模板路径',
  `template_engine` VARCHAR(64) DEFAULT NULL COMMENT '模板引擎',
  `template_content` LONGTEXT DEFAULT NULL COMMENT '模板内容',
  `sort_order` INT DEFAULT NULL COMMENT '排序',
  `enabled` TINYINT(1) DEFAULT 1 COMMENT '是否启用',
  `metadata_json` TEXT DEFAULT NULL COMMENT '扩展元数据',
  `create_name` VARCHAR(255) DEFAULT NULL,
  `create_by` INT DEFAULT NULL,
  `create_time` DATETIME DEFAULT NULL,
  `update_time` DATETIME DEFAULT NULL,
  `update_name` VARCHAR(255) DEFAULT NULL,
  `update_by` INT DEFAULT NULL,
  PRIMARY KEY (`soft_package_profile_template_id`),
  KEY `idx_soft_profile_template_profile_id` (`soft_package_profile_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='软件画像模板';

CREATE TABLE IF NOT EXISTS `soft_package_version` (
  `soft_package_version_id` INT NOT NULL AUTO_INCREMENT COMMENT '版本ID',
  `soft_package_id` INT DEFAULT NULL COMMENT '软件ID',
  `version_code` VARCHAR(255) DEFAULT NULL COMMENT '版本编码',
  `version_name` VARCHAR(255) DEFAULT NULL COMMENT '版本名称',
  `package_name` VARCHAR(255) DEFAULT NULL COMMENT '版本软件名称',
  `os_type` VARCHAR(64) DEFAULT NULL COMMENT '版本操作系统',
  `architecture` VARCHAR(64) DEFAULT NULL COMMENT '版本架构',
  `source_kind` VARCHAR(64) DEFAULT NULL COMMENT '来源分类',
  `install_mode` VARCHAR(64) DEFAULT NULL COMMENT '安装模式',
  `repository_source_id` INT DEFAULT NULL COMMENT '来源ID',
  `artifact_path` VARCHAR(1024) DEFAULT NULL COMMENT '本地包路径',
  `download_url` VARCHAR(1024) DEFAULT NULL COMMENT '远程下载地址',
  `template_from_version_id` INT DEFAULT NULL COMMENT '模板来源版本ID',
  `download_urls_json` TEXT DEFAULT NULL COMMENT '下载地址JSON',
  `md5` VARCHAR(128) DEFAULT NULL COMMENT 'MD5',
  `sha256` VARCHAR(255) DEFAULT NULL COMMENT 'SHA256',
  `install_script` LONGTEXT DEFAULT NULL COMMENT '安装脚本',
  `uninstall_script` LONGTEXT DEFAULT NULL COMMENT '卸载脚本',
  `start_script` LONGTEXT DEFAULT NULL COMMENT '启动脚本',
  `stop_script` LONGTEXT DEFAULT NULL COMMENT '停止脚本',
  `restart_script` LONGTEXT DEFAULT NULL COMMENT '重启脚本',
  `status_script` LONGTEXT DEFAULT NULL COMMENT '状态脚本',
  `service_register_script` LONGTEXT DEFAULT NULL COMMENT '服务注册脚本',
  `service_unregister_script` LONGTEXT DEFAULT NULL COMMENT '服务卸载脚本',
  `log_paths_json` TEXT DEFAULT NULL COMMENT '日志路径JSON',
  `config_paths_json` TEXT DEFAULT NULL COMMENT '配置路径JSON',
  `capability_flags_json` TEXT DEFAULT NULL COMMENT '能力标记JSON',
  `metadata_json` TEXT DEFAULT NULL COMMENT '扩展元数据',
  `enabled` TINYINT(1) DEFAULT 1 COMMENT '是否启用',
  `create_name` VARCHAR(255) DEFAULT NULL,
  `create_by` INT DEFAULT NULL,
  `create_time` DATETIME DEFAULT NULL,
  `update_time` DATETIME DEFAULT NULL,
  `update_name` VARCHAR(255) DEFAULT NULL,
  `update_by` INT DEFAULT NULL,
  PRIMARY KEY (`soft_package_version_id`),
  UNIQUE KEY `uk_soft_package_version` (`soft_package_id`, `version_code`, `package_name`, `os_type`, `architecture`),
  KEY `idx_soft_package_version_lookup` (`soft_package_id`, `version_code`, `os_type`, `architecture`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='软件版本档';

CREATE TABLE IF NOT EXISTS `soft_target` (
  `soft_target_id` INT NOT NULL AUTO_INCREMENT COMMENT '目标ID',
  `target_name` VARCHAR(255) DEFAULT NULL COMMENT '目标名称',
  `target_code` VARCHAR(255) DEFAULT NULL COMMENT '目标编码',
  `target_type` VARCHAR(64) DEFAULT NULL COMMENT '目标类型',
  `os_type` VARCHAR(64) DEFAULT NULL COMMENT '操作系统',
  `architecture` VARCHAR(64) DEFAULT NULL COMMENT '架构',
  `host` VARCHAR(255) DEFAULT NULL COMMENT '主机',
  `port` INT DEFAULT NULL COMMENT '端口',
  `username` VARCHAR(255) DEFAULT NULL COMMENT '账号',
  `password` VARCHAR(2048) DEFAULT NULL COMMENT '密码密文',
  `private_key` LONGTEXT DEFAULT NULL COMMENT '私钥密文',
  `base_directory` VARCHAR(1024) DEFAULT NULL COMMENT '基础目录',
  `enabled` TINYINT(1) DEFAULT 1 COMMENT '是否启用',
  `description` VARCHAR(1024) DEFAULT NULL COMMENT '描述',
  `metadata_json` TEXT DEFAULT NULL COMMENT '扩展元数据',
  `create_name` VARCHAR(255) DEFAULT NULL,
  `create_by` INT DEFAULT NULL,
  `create_time` DATETIME DEFAULT NULL,
  `update_time` DATETIME DEFAULT NULL,
  `update_name` VARCHAR(255) DEFAULT NULL,
  `update_by` INT DEFAULT NULL,
  PRIMARY KEY (`soft_target_id`),
  UNIQUE KEY `uk_soft_target_code` (`target_code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='软件安装目标';

CREATE TABLE IF NOT EXISTS `soft_installation` (
  `soft_installation_id` INT NOT NULL AUTO_INCREMENT COMMENT '安装ID',
  `soft_package_id` INT DEFAULT NULL COMMENT '软件ID',
  `soft_package_version_id` INT DEFAULT NULL COMMENT '版本ID',
  `soft_target_id` INT DEFAULT NULL COMMENT '目标ID',
  `installation_name` VARCHAR(255) DEFAULT NULL COMMENT '实例名称',
  `install_path` VARCHAR(1024) DEFAULT NULL COMMENT '安装路径',
  `service_name` VARCHAR(255) DEFAULT NULL COMMENT '服务名称',
  `install_options_json` LONGTEXT DEFAULT NULL COMMENT '安装参数快照JSON',
  `service_options_json` LONGTEXT DEFAULT NULL COMMENT '服务参数快照JSON',
  `config_options_json` LONGTEXT DEFAULT NULL COMMENT '配置参数快照JSON',
  `template_summary_json` LONGTEXT DEFAULT NULL COMMENT '模板摘要JSON',
  `install_status` VARCHAR(64) DEFAULT NULL COMMENT '安装状态',
  `runtime_status` VARCHAR(64) DEFAULT NULL COMMENT '运行状态',
  `installed_version` VARCHAR(255) DEFAULT NULL COMMENT '已安装版本',
  `installed_time` DATETIME DEFAULT NULL COMMENT '安装时间',
  `last_operation_time` DATETIME DEFAULT NULL COMMENT '最后操作时间',
  `last_operation_message` VARCHAR(2048) DEFAULT NULL COMMENT '最后操作说明',
  `create_name` VARCHAR(255) DEFAULT NULL,
  `create_by` INT DEFAULT NULL,
  `create_time` DATETIME DEFAULT NULL,
  `update_time` DATETIME DEFAULT NULL,
  `update_name` VARCHAR(255) DEFAULT NULL,
  `update_by` INT DEFAULT NULL,
  PRIMARY KEY (`soft_installation_id`),
  KEY `idx_soft_installation_target_id` (`soft_target_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='软件安装实例';

CREATE TABLE IF NOT EXISTS `soft_operation_log` (
  `soft_operation_log_id` INT NOT NULL AUTO_INCREMENT COMMENT '操作日志ID',
  `soft_installation_id` INT DEFAULT NULL COMMENT '安装ID',
  `soft_target_id` INT DEFAULT NULL COMMENT '目标ID',
  `soft_package_version_id` INT DEFAULT NULL COMMENT '版本ID',
  `operation_type` VARCHAR(64) DEFAULT NULL COMMENT '操作类型',
  `operation_status` VARCHAR(64) DEFAULT NULL COMMENT '操作状态',
  `operation_command` LONGTEXT DEFAULT NULL COMMENT '执行命令',
  `operation_message` VARCHAR(2048) DEFAULT NULL COMMENT '执行说明',
  `operation_stage` VARCHAR(64) DEFAULT NULL COMMENT '执行阶段',
  `progress_percent` INT DEFAULT NULL COMMENT '执行进度',
  `detail_message` VARCHAR(2048) DEFAULT NULL COMMENT '详细说明',
  `operation_output` LONGTEXT DEFAULT NULL COMMENT '执行输出',
  `template_summary_json` LONGTEXT DEFAULT NULL COMMENT '模板摘要JSON',
  `parameter_summary_json` LONGTEXT DEFAULT NULL COMMENT '参数摘要JSON',
  `start_time` DATETIME DEFAULT NULL COMMENT '开始时间',
  `end_time` DATETIME DEFAULT NULL COMMENT '结束时间',
  `create_name` VARCHAR(255) DEFAULT NULL,
  `create_by` INT DEFAULT NULL,
  `create_time` DATETIME DEFAULT NULL,
  `update_time` DATETIME DEFAULT NULL,
  `update_name` VARCHAR(255) DEFAULT NULL,
  `update_by` INT DEFAULT NULL,
  PRIMARY KEY (`soft_operation_log_id`),
  KEY `idx_soft_operation_installation` (`soft_installation_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='软件操作日志';

CREATE TABLE IF NOT EXISTS `soft_config_snapshot` (
  `soft_config_snapshot_id` INT NOT NULL AUTO_INCREMENT COMMENT '快照ID',
  `soft_installation_id` INT DEFAULT NULL COMMENT '安装ID',
  `config_path` VARCHAR(1024) DEFAULT NULL COMMENT '配置路径',
  `snapshot_name` VARCHAR(255) DEFAULT NULL COMMENT '快照名称',
  `config_content` LONGTEXT DEFAULT NULL COMMENT '配置内容',
  `operation_remark` VARCHAR(1024) DEFAULT NULL COMMENT '备注',
  `create_name` VARCHAR(255) DEFAULT NULL,
  `create_by` INT DEFAULT NULL,
  `create_time` DATETIME DEFAULT NULL,
  `update_time` DATETIME DEFAULT NULL,
  `update_name` VARCHAR(255) DEFAULT NULL,
  `update_by` INT DEFAULT NULL,
  PRIMARY KEY (`soft_config_snapshot_id`),
  KEY `idx_soft_config_installation` (`soft_installation_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='软件配置快照';

SET FOREIGN_KEY_CHECKS = 1;
