services:
  guacamole-postgres:
    image: postgres:13
    container_name: guacamole-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${GUACAMOLE_DB_NAME}
      POSTGRES_USER: ${GUACAMOLE_DB_USERNAME}
      POSTGRES_PASSWORD: ${GUACAMOLE_DB_PASSWORD}
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d:ro
      - guacamole-postgres-data:/var/lib/postgresql/data
    networks:
      - guacamole-net

  guacd:
    image: guacamole/guacd:1.6.0
    container_name: guacd
    restart: unless-stopped
    networks:
      - guacamole-net

  guacamole:
    image: guacamole/guacamole:1.5.5
    container_name: guacamole
    restart: unless-stopped
    depends_on:
      - guacamole-postgres
      - guacd
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRESQL_HOSTNAME: guacamole-postgres
      POSTGRESQL_DATABASE: ${GUACAMOLE_DB_NAME}
      POSTGRESQL_USER: ${GUACAMOLE_DB_USERNAME}
      POSTGRESQL_PASSWORD: ${GUACAMOLE_DB_PASSWORD}
      WEBAPP_CONTEXT: guacamole
    ports:
      - "${GUACAMOLE_HTTP_PORT}:8080"
    networks:
      - guacamole-net

networks:
  guacamole-net:
    driver: bridge

volumes:
  guacamole-postgres-data:
