-- 支付系统数据库表结构
-- 更新时间: 2026-03-19
-- 说明: 商户、支付方式、订单、状态日志、交易流水

CREATE TABLE IF NOT EXISTS `merchant` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `merchant_no` VARCHAR(32) NOT NULL UNIQUE COMMENT '商户号',
  `merchant_name` VARCHAR(100) NOT NULL COMMENT '商户名称',
  `contact_name` VARCHAR(50) DEFAULT NULL COMMENT '联系人',
  `contact_phone` VARCHAR(20) DEFAULT NULL COMMENT '联系电话',
  `contact_email` VARCHAR(100) DEFAULT NULL COMMENT '联系邮箱',
  `business_license` VARCHAR(200) DEFAULT NULL COMMENT '营业执照',
  `legal_person` VARCHAR(50) DEFAULT NULL COMMENT '法人',
  `default_notify_url` VARCHAR(255) DEFAULT NULL COMMENT '默认支付回调地址',
  `default_return_url` VARCHAR(255) DEFAULT NULL COMMENT '默认支付返回地址',
  `payment_wallet_enabled` TINYINT DEFAULT 0 COMMENT '钱包能力开关',
  `payment_auto_close_enabled` TINYINT DEFAULT 1 COMMENT '自动关单开关',
  `payment_auto_close_minutes` INT DEFAULT 30 COMMENT '自动关单分钟数',
  `payment_split_table_enabled` TINYINT DEFAULT 0 COMMENT '自动分表能力开关',
  `payment_profit_sharing_enabled` TINYINT DEFAULT 0 COMMENT '自动分账能力开关',
  `payment_coupon_enabled` TINYINT DEFAULT 0 COMMENT '优惠能力开关',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `status` TINYINT DEFAULT 0 COMMENT '状态:0待审核 1已激活 2已停用 3已注销',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  INDEX `idx_merchant_no` (`merchant_no`),
  INDEX `idx_merchant_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='支付商户表';

CREATE TABLE IF NOT EXISTS `merchant_channel` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `merchant_id` BIGINT NOT NULL COMMENT '商户ID',
  `channel_type` VARCHAR(32) NOT NULL COMMENT '渠道类型',
  `channel_sub_type` VARCHAR(32) NOT NULL COMMENT '渠道子类型',
  `channel_name` VARCHAR(100) NOT NULL COMMENT '渠道名称',
  `app_id` VARCHAR(120) DEFAULT NULL COMMENT '应用ID',
  `merchant_no` VARCHAR(120) DEFAULT NULL COMMENT '商户号/PID/路由标识',
  `api_key` TEXT DEFAULT NULL COMMENT 'API Key(加密)',
  `private_key` TEXT DEFAULT NULL COMMENT '私钥(加密)',
  `public_key` TEXT DEFAULT NULL COMMENT '公钥',
  `cert_path` VARCHAR(255) DEFAULT NULL COMMENT '证书路径',
  `sandbox_mode` TINYINT DEFAULT 0 COMMENT '沙箱模式:0正式 1沙箱',
  `notify_url` VARCHAR(255) DEFAULT NULL COMMENT '渠道专属回调地址',
  `return_url` VARCHAR(255) DEFAULT NULL COMMENT '渠道专属返回地址',
  `status` TINYINT DEFAULT 0 COMMENT '状态:0禁用 1启用',
  `ext_config` TEXT DEFAULT NULL COMMENT '扩展配置JSON',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  INDEX `idx_channel_merchant_id` (`merchant_id`),
  INDEX `idx_channel_type` (`channel_type`),
  INDEX `idx_channel_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商户支付方式配置表';

CREATE TABLE IF NOT EXISTS `payment_order` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `order_no` VARCHAR(40) NOT NULL UNIQUE COMMENT '平台订单号',
  `business_order_no` VARCHAR(64) DEFAULT NULL COMMENT '业务订单号',
  `merchant_id` BIGINT NOT NULL COMMENT '商户ID',
  `channel_id` BIGINT DEFAULT NULL COMMENT '支付方式ID',
  `user_id` BIGINT DEFAULT NULL COMMENT '用户ID',
  `channel_type` VARCHAR(32) NOT NULL COMMENT '支付渠道类型',
  `channel_sub_type` VARCHAR(32) DEFAULT NULL COMMENT '支付渠道子类型',
  `order_amount` DECIMAL(18,2) NOT NULL COMMENT '订单金额',
  `paid_amount` DECIMAL(18,2) DEFAULT 0 COMMENT '实付金额',
  `refund_amount` DECIMAL(18,2) DEFAULT 0 COMMENT '已退金额',
  `discount_amount` DECIMAL(18,2) DEFAULT 0 COMMENT '优惠金额',
  `currency` VARCHAR(16) DEFAULT 'CNY' COMMENT '币种',
  `status` VARCHAR(32) DEFAULT 'PENDING' COMMENT '订单状态',
  `subject` VARCHAR(200) DEFAULT NULL COMMENT '订单标题',
  `body` VARCHAR(500) DEFAULT NULL COMMENT '订单描述',
  `notify_url` VARCHAR(255) DEFAULT NULL COMMENT '支付回调地址',
  `return_url` VARCHAR(255) DEFAULT NULL COMMENT '返回地址',
  `expire_time` DATETIME DEFAULT NULL COMMENT '过期时间',
  `pay_time` DATETIME DEFAULT NULL COMMENT '支付时间',
  `complete_time` DATETIME DEFAULT NULL COMMENT '完成时间',
  `refund_time` DATETIME DEFAULT NULL COMMENT '退款时间',
  `third_party_order_no` VARCHAR(100) DEFAULT NULL COMMENT '第三方订单号',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `deleted` TINYINT DEFAULT 0 COMMENT '删除标记:0未删 1已删',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  INDEX `idx_payment_order_no` (`order_no`),
  UNIQUE KEY `uk_payment_order_merchant_business_no` (`merchant_id`, `business_order_no`),
  INDEX `idx_payment_merchant_id` (`merchant_id`),
  INDEX `idx_payment_status` (`status`),
  INDEX `idx_payment_deleted` (`deleted`),
  INDEX `idx_payment_timeout_scan` (`status`, `deleted`, `expire_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='支付订单表';

CREATE TABLE IF NOT EXISTS `order_state_log` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `order_id` BIGINT NOT NULL COMMENT '订单ID',
  `from_state` VARCHAR(32) DEFAULT NULL COMMENT '原状态',
  `to_state` VARCHAR(32) NOT NULL COMMENT '目标状态',
  `event` VARCHAR(50) NOT NULL COMMENT '触发事件',
  `operator` VARCHAR(100) DEFAULT NULL COMMENT '操作人',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  INDEX `idx_state_log_order_id` (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单状态流转日志表';

CREATE TABLE IF NOT EXISTS `transaction_record` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `transaction_no` VARCHAR(40) NOT NULL UNIQUE COMMENT '流水号',
  `order_id` BIGINT NOT NULL COMMENT '订单ID',
  `order_no` VARCHAR(40) NOT NULL COMMENT '订单号',
  `merchant_id` BIGINT NOT NULL COMMENT '商户ID',
  `channel_id` BIGINT DEFAULT NULL COMMENT '支付方式ID',
  `transaction_type` VARCHAR(32) NOT NULL COMMENT '交易类型',
  `amount` DECIMAL(18,2) NOT NULL COMMENT '交易金额',
  `channel_type` VARCHAR(32) NOT NULL COMMENT '渠道类型',
  `third_party_transaction_no` VARCHAR(100) DEFAULT NULL COMMENT '第三方流水号',
  `status` TINYINT DEFAULT 2 COMMENT '状态:0失败 1成功 2处理中',
  `request_payload` TEXT DEFAULT NULL COMMENT '请求快照',
  `response_payload` TEXT DEFAULT NULL COMMENT '响应快照',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  INDEX `idx_transaction_no` (`transaction_no`),
  INDEX `idx_transaction_order_no` (`order_no`),
  INDEX `idx_transaction_merchant_id` (`merchant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='交易流水表';

CREATE TABLE IF NOT EXISTS `wallet_account` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `merchant_id` BIGINT NOT NULL COMMENT '商户ID',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `available_balance` DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '可用余额',
  `frozen_balance` DECIMAL(18,2) NOT NULL DEFAULT 0 COMMENT '冻结余额',
  `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态:1启用 0禁用',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  UNIQUE KEY `uk_wallet_account_merchant_user` (`merchant_id`, `user_id`),
  INDEX `idx_wallet_account_merchant` (`merchant_id`),
  INDEX `idx_wallet_account_user` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='钱包账户表';

CREATE TABLE IF NOT EXISTS `wallet_account_log` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `merchant_id` BIGINT NOT NULL COMMENT '商户ID',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `biz_type` VARCHAR(32) NOT NULL COMMENT '业务类型:RECHARGE/PAY/REFUND',
  `biz_no` VARCHAR(64) NOT NULL COMMENT '业务单号',
  `change_type` VARCHAR(16) NOT NULL COMMENT '变动方向:IN/OUT',
  `change_amount` DECIMAL(18,2) NOT NULL COMMENT '变动金额',
  `balance_before` DECIMAL(18,2) NOT NULL COMMENT '变动前余额',
  `balance_after` DECIMAL(18,2) NOT NULL COMMENT '变动后余额',
  `operator` VARCHAR(100) DEFAULT NULL COMMENT '操作人',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  UNIQUE KEY `uk_wallet_log_merchant_user_biz` (`merchant_id`, `user_id`, `biz_type`, `biz_no`),
  INDEX `idx_wallet_log_merchant_user` (`merchant_id`, `user_id`),
  INDEX `idx_wallet_log_biz` (`biz_type`, `biz_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='钱包账户流水表';

CREATE TABLE IF NOT EXISTS `merchant_payment_config` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
  `merchant_id` BIGINT NOT NULL COMMENT '商户ID',
  `order_reusable` TINYINT DEFAULT 1 COMMENT '订单是否可重复支付',
  `order_timeout_minutes` INT DEFAULT NULL COMMENT '订单超时时间(分钟)',
  `pending_order_limit` INT DEFAULT NULL COMMENT '待支付订单数量限制',
  `auto_cancel_timeout_order` TINYINT DEFAULT 1 COMMENT '是否自动取消超时订单',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_by` VARCHAR(64) DEFAULT NULL COMMENT '创建人',
  `update_by` VARCHAR(64) DEFAULT NULL COMMENT '更新人',
  `create_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人姓名',
  `update_name` VARCHAR(64) DEFAULT NULL COMMENT '更新人姓名',
  UNIQUE KEY `uk_merchant_payment_config_merchant` (`merchant_id`),
  INDEX `idx_merchant_payment_config_tenant_merchant` (`tenant_id`, `merchant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商户支付配置表';

CREATE TABLE IF NOT EXISTS `payment_global_config` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `config_key` VARCHAR(32) NOT NULL COMMENT '配置标识',
  `payment_notify_base_url` VARCHAR(255) DEFAULT NULL COMMENT '默认回调基础地址',
  `payment_return_url` VARCHAR(255) DEFAULT NULL COMMENT '默认返回地址',
  `payment_callback_path_template` VARCHAR(128) DEFAULT '/{orderNo}/{merchantId}' COMMENT '回调路径模板',
  `payment_auto_refresh_seconds` INT DEFAULT 60 COMMENT '默认自动刷新秒数',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  UNIQUE KEY `uk_payment_global_config_key` (`config_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='支付全局配置表';

CREATE TABLE IF NOT EXISTS `payment_refund_order` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `refund_no` VARCHAR(40) NOT NULL COMMENT '退款单号',
  `order_id` BIGINT NOT NULL COMMENT '支付订单ID',
  `order_no` VARCHAR(40) NOT NULL COMMENT '支付订单号',
  `merchant_id` BIGINT NOT NULL COMMENT '商户ID',
  `channel_id` BIGINT DEFAULT NULL COMMENT '支付方式ID',
  `source_order_status` VARCHAR(32) DEFAULT NULL COMMENT '发起退款前订单状态',
  `third_party_refund_no` VARCHAR(100) DEFAULT NULL COMMENT '第三方退款单号',
  `refund_amount` DECIMAL(18,2) NOT NULL COMMENT '退款金额',
  `status` VARCHAR(32) NOT NULL DEFAULT 'PROCESSING' COMMENT '退款状态',
  `reason` VARCHAR(500) DEFAULT NULL COMMENT '退款原因',
  `notify_status` TINYINT NOT NULL DEFAULT 0 COMMENT '回调状态',
  `request_payload` TEXT DEFAULT NULL COMMENT '退款请求快照',
  `response_payload` TEXT DEFAULT NULL COMMENT '退款响应快照',
  `operator` VARCHAR(100) DEFAULT NULL COMMENT '操作人',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  UNIQUE KEY `uk_payment_refund_order_refund_no` (`refund_no`),
  INDEX `idx_payment_refund_order_order` (`order_id`, `created_at`),
  INDEX `idx_payment_refund_order_status` (`status`, `updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='支付退款单表';

CREATE TABLE IF NOT EXISTS `payment_notify_log` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `notify_type` VARCHAR(32) NOT NULL COMMENT '通知类型',
  `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
  `merchant_id` BIGINT DEFAULT NULL COMMENT '商户ID',
  `channel_id` BIGINT DEFAULT NULL COMMENT '支付方式ID',
  `channel_type` VARCHAR(32) DEFAULT NULL COMMENT '渠道类型',
  `channel_sub_type` VARCHAR(32) DEFAULT NULL COMMENT '渠道子类型',
  `order_id` BIGINT DEFAULT NULL COMMENT '订单ID',
  `order_no` VARCHAR(64) DEFAULT NULL COMMENT '订单号',
  `refund_id` BIGINT DEFAULT NULL COMMENT '退款单ID',
  `refund_no` VARCHAR(64) DEFAULT NULL COMMENT '退款单号',
  `third_party_trade_no` VARCHAR(128) DEFAULT NULL COMMENT '第三方交易号',
  `request_headers` TEXT DEFAULT NULL COMMENT '请求头',
  `request_body` LONGTEXT DEFAULT NULL COMMENT '请求体',
  `request_params` TEXT DEFAULT NULL COMMENT '请求参数',
  `sign_verified` TINYINT DEFAULT 0 COMMENT '验签结果',
  `process_status` VARCHAR(32) DEFAULT 'PROCESSING' COMMENT '处理状态',
  `process_result` TEXT DEFAULT NULL COMMENT '处理结果',
  `error_message` VARCHAR(512) DEFAULT NULL COMMENT '错误信息',
  `retry_count` INT DEFAULT 0 COMMENT '重试次数',
  `received_at` DATETIME DEFAULT NULL COMMENT '接收时间',
  `processed_at` DATETIME DEFAULT NULL COMMENT '处理时间',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `related_order_id` BIGINT DEFAULT NULL COMMENT '关联订单ID',
  `related_refund_id` BIGINT DEFAULT NULL COMMENT '关联退款单ID',
  `received_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '兼容旧字段-接收时间',
  `processed_time` DATETIME DEFAULT NULL COMMENT '兼容旧字段-处理时间',
  INDEX `idx_payment_notify_log_tenant_merchant` (`tenant_id`, `merchant_id`),
  INDEX `idx_payment_notify_log_order` (`order_no`),
  INDEX `idx_payment_notify_log_refund` (`refund_no`),
  INDEX `idx_payment_notify_log_status` (`process_status`),
  INDEX `idx_payment_notify_log_received` (`received_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='支付回调日志表';

CREATE TABLE IF NOT EXISTS `payment_notify_error` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `notify_log_id` BIGINT NOT NULL COMMENT '回调日志ID',
  `notify_type` VARCHAR(32) NOT NULL COMMENT '通知类型',
  `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
  `merchant_id` BIGINT DEFAULT NULL COMMENT '商户ID',
  `order_no` VARCHAR(64) DEFAULT NULL COMMENT '订单号',
  `refund_no` VARCHAR(64) DEFAULT NULL COMMENT '退款单号',
  `error_type` VARCHAR(64) NOT NULL COMMENT '错误类型',
  `error_message` TEXT DEFAULT NULL COMMENT '错误信息',
  `error_stack` LONGTEXT DEFAULT NULL COMMENT '错误堆栈',
  `request_data` LONGTEXT DEFAULT NULL COMMENT '请求数据',
  `retry_count` INT DEFAULT 0 COMMENT '重试次数',
  `max_retry_count` INT DEFAULT 5 COMMENT '最大重试次数',
  `next_retry_time` DATETIME DEFAULT NULL COMMENT '下次重试时间',
  `status` VARCHAR(32) NOT NULL COMMENT '状态',
  `resolved_at` DATETIME DEFAULT NULL COMMENT '解决时间',
  `resolved_by` VARCHAR(64) DEFAULT NULL COMMENT '解决人',
  `remark` VARCHAR(512) DEFAULT NULL COMMENT '备注',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  INDEX `idx_payment_notify_error_log` (`notify_log_id`),
  INDEX `idx_payment_notify_error_status` (`status`),
  INDEX `idx_payment_notify_error_retry` (`next_retry_time`),
  INDEX `idx_payment_notify_error_tenant_merchant` (`tenant_id`, `merchant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='支付回调异常表';

CREATE TABLE IF NOT EXISTS `wallet_order` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `order_no` VARCHAR(64) NOT NULL COMMENT '订单号',
  `order_type` VARCHAR(32) NOT NULL COMMENT '订单类型',
  `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
  `merchant_id` BIGINT NOT NULL COMMENT '商户ID',
  `user_id` BIGINT NOT NULL COMMENT '用户ID',
  `related_user_id` BIGINT DEFAULT NULL COMMENT '关联用户ID',
  `amount` DECIMAL(15,2) NOT NULL COMMENT '金额',
  `status` VARCHAR(32) NOT NULL COMMENT '状态',
  `third_party_order_no` VARCHAR(128) DEFAULT NULL COMMENT '第三方订单号',
  `bank_account` VARCHAR(64) DEFAULT NULL COMMENT '银行账号',
  `bank_name` VARCHAR(128) DEFAULT NULL COMMENT '银行名称',
  `account_name` VARCHAR(64) DEFAULT NULL COMMENT '账户名',
  `request_payload` TEXT DEFAULT NULL COMMENT '请求报文',
  `response_payload` TEXT DEFAULT NULL COMMENT '响应报文',
  `operator` VARCHAR(64) DEFAULT NULL COMMENT '操作人',
  `remark` VARCHAR(512) DEFAULT NULL COMMENT '备注',
  `completed_at` DATETIME DEFAULT NULL COMMENT '完成时间',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_by` VARCHAR(64) DEFAULT NULL COMMENT '创建人',
  `update_by` VARCHAR(64) DEFAULT NULL COMMENT '更新人',
  `create_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人姓名',
  `update_name` VARCHAR(64) DEFAULT NULL COMMENT '更新人姓名',
  UNIQUE KEY `uk_wallet_order_no` (`order_no`),
  INDEX `idx_wallet_order_tenant_merchant` (`tenant_id`, `merchant_id`),
  INDEX `idx_wallet_order_user` (`user_id`),
  INDEX `idx_wallet_order_type` (`order_type`),
  INDEX `idx_wallet_order_status` (`status`),
  INDEX `idx_wallet_order_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='钱包订单表';

CREATE TABLE IF NOT EXISTS `merchant_wallet_limit` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `tenant_id` BIGINT DEFAULT NULL COMMENT '租户ID',
  `merchant_id` BIGINT NOT NULL COMMENT '商户ID',
  `single_recharge_limit` DECIMAL(15,2) DEFAULT NULL COMMENT '单笔充值限额',
  `daily_recharge_limit` DECIMAL(15,2) DEFAULT NULL COMMENT '日充值限额',
  `single_withdraw_limit` DECIMAL(15,2) DEFAULT NULL COMMENT '单笔提现限额',
  `daily_withdraw_limit` DECIMAL(15,2) DEFAULT NULL COMMENT '日提现限额',
  `single_transfer_limit` DECIMAL(15,2) DEFAULT NULL COMMENT '单笔转账限额',
  `daily_transfer_limit` DECIMAL(15,2) DEFAULT NULL COMMENT '日转账限额',
  `balance_limit` DECIMAL(15,2) DEFAULT NULL COMMENT '余额上限',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `create_by` VARCHAR(64) DEFAULT NULL COMMENT '创建人',
  `update_by` VARCHAR(64) DEFAULT NULL COMMENT '更新人',
  `create_name` VARCHAR(64) DEFAULT NULL COMMENT '创建人姓名',
  `update_name` VARCHAR(64) DEFAULT NULL COMMENT '更新人姓名',
  UNIQUE KEY `uk_merchant_wallet_limit_merchant` (`merchant_id`),
  INDEX `idx_merchant_wallet_limit_tenant_merchant` (`tenant_id`, `merchant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商户钱包限额配置表';

CREATE TABLE IF NOT EXISTS `wechat_pay_score_order` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `merchant_id` BIGINT NOT NULL COMMENT '商户ID',
  `channel_id` BIGINT NOT NULL COMMENT '渠道ID',
  `user_id` BIGINT DEFAULT NULL COMMENT '用户ID',
  `out_order_no` VARCHAR(64) NOT NULL COMMENT '商户服务订单号',
  `service_order_no` VARCHAR(64) DEFAULT NULL COMMENT '微信支付分服务订单号',
  `app_id` VARCHAR(128) DEFAULT NULL COMMENT '应用ID',
  `service_id` VARCHAR(128) NOT NULL COMMENT '支付分服务ID',
  `open_id` VARCHAR(128) NOT NULL COMMENT '用户openId',
  `state` VARCHAR(32) NOT NULL COMMENT '订单状态',
  `total_amount` DECIMAL(15,2) DEFAULT NULL COMMENT '金额',
  `notify_url` VARCHAR(255) DEFAULT NULL COMMENT '回调地址',
  `service_introduction` VARCHAR(255) DEFAULT NULL COMMENT '服务介绍',
  `start_time` VARCHAR(64) DEFAULT NULL COMMENT '服务开始时间',
  `end_time` VARCHAR(64) DEFAULT NULL COMMENT '服务结束时间',
  `finish_type` VARCHAR(32) DEFAULT NULL COMMENT '完结类型',
  `reason` VARCHAR(255) DEFAULT NULL COMMENT '原因',
  `finish_reason` VARCHAR(255) DEFAULT NULL COMMENT '完成原因',
  `package_info` VARCHAR(512) DEFAULT NULL COMMENT '拉起参数',
  `attach` VARCHAR(255) DEFAULT NULL COMMENT '附加数据',
  `request_payload` LONGTEXT DEFAULT NULL COMMENT '请求报文',
  `response_payload` LONGTEXT DEFAULT NULL COMMENT '响应报文',
  `remark` VARCHAR(512) DEFAULT NULL COMMENT '备注',
  `completed_at` DATETIME DEFAULT NULL COMMENT '完成时间',
  `cancelled_at` DATETIME DEFAULT NULL COMMENT '取消时间',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  UNIQUE KEY `uk_wechat_pay_score_order_no` (`out_order_no`),
  INDEX `idx_wechat_pay_score_merchant` (`merchant_id`, `create_time`),
  INDEX `idx_wechat_pay_score_channel` (`channel_id`, `create_time`),
  INDEX `idx_wechat_pay_score_open` (`open_id`),
  INDEX `idx_wechat_pay_score_state` (`state`, `update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='微信支付分订单表';

CREATE TABLE IF NOT EXISTS `payment_scheduler_config` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `task_key` VARCHAR(64) NOT NULL COMMENT '任务编码',
  `task_name` VARCHAR(128) NOT NULL COMMENT '任务名称',
  `cron_expression` VARCHAR(64) NOT NULL COMMENT 'Cron表达式',
  `enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
  `description` VARCHAR(512) DEFAULT NULL COMMENT '任务说明',
  `last_started_at` DATETIME DEFAULT NULL COMMENT '最近开始执行时间',
  `last_finished_at` DATETIME DEFAULT NULL COMMENT '最近完成时间',
  `last_run_status` VARCHAR(32) DEFAULT NULL COMMENT '最近运行状态',
  `last_run_message` VARCHAR(512) DEFAULT NULL COMMENT '最近运行结果',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  UNIQUE KEY `uk_payment_scheduler_task_key` (`task_key`),
  INDEX `idx_payment_scheduler_enabled` (`enabled`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='支付调度任务配置表';

CREATE TABLE IF NOT EXISTS `payment_partition_config` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `business_type` VARCHAR(32) NOT NULL COMMENT '业务类型: ORDER/TRANSACTION',
  `source_table` VARCHAR(64) NOT NULL COMMENT '源表名',
  `partition_prefix` VARCHAR(64) NOT NULL COMMENT '分表前缀',
  `partition_granularity` VARCHAR(16) NOT NULL DEFAULT 'MONTH' COMMENT '分表粒度: MONTH/DAY',
  `retention_days` INT NOT NULL DEFAULT 365 COMMENT '保留天数',
  `create_ahead_days` INT NOT NULL DEFAULT 7 COMMENT '提前建表天数',
  `migrate_before_days` INT NOT NULL DEFAULT 90 COMMENT '迁移阈值天数',
  `auto_create_enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否自动建表',
  `auto_migrate_enabled` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否自动迁移',
  `keep_source_data` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '迁移后是否保留主表数据',
  `create_task_key` VARCHAR(80) DEFAULT NULL COMMENT '自动建表任务Key',
  `migrate_task_key` VARCHAR(80) DEFAULT NULL COMMENT '迁移任务Key',
  `last_partition_table` VARCHAR(80) DEFAULT NULL COMMENT '最近分表名',
  `last_partition_at` DATETIME DEFAULT NULL COMMENT '最近建表时间',
  `last_migrate_at` DATETIME DEFAULT NULL COMMENT '最近迁移时间',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  UNIQUE KEY `uk_payment_partition_business_type` (`business_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='订单与流水分表配置表';

CREATE TABLE IF NOT EXISTS `payment_sys_job` (
  `job_id` INT NOT NULL AUTO_INCREMENT COMMENT '任务ID',
  `job_no` VARCHAR(64) NOT NULL COMMENT '任务编号',
  `job_name` VARCHAR(255) DEFAULT NULL COMMENT '任务名称',
  `job_schedule_type` VARCHAR(50) DEFAULT 'CRON' COMMENT '调度类型',
  `job_schedule_time` VARCHAR(255) DEFAULT NULL COMMENT '调度配置',
  `job_author` VARCHAR(100) DEFAULT NULL COMMENT '负责人',
  `job_alarm_email` VARCHAR(255) DEFAULT NULL COMMENT '报警邮件',
  `job_trigger_status` TINYINT(1) DEFAULT 0 COMMENT '调度状态 0-停止 1-运行中',
  `job_desc` VARCHAR(500) DEFAULT NULL COMMENT '任务描述',
  `job_glue_updatetime` DATETIME DEFAULT NULL COMMENT 'GLUE更新时间',
  `job_glue_source` TEXT DEFAULT NULL COMMENT 'GLUE源码',
  `job_glue_type` VARCHAR(50) DEFAULT 'BEAN' COMMENT 'GLUE类型',
  `job_dispatch_mode` VARCHAR(20) DEFAULT 'LOCAL' COMMENT '分发模式 LOCAL-本地轮询 REMOTE-远程推送',
  `job_remote_executor_address` VARCHAR(500) DEFAULT NULL COMMENT '远程执行器地址',
  `job_storage_mode` VARCHAR(20) DEFAULT 'DATABASE' COMMENT '存储模式 DATABASE/REDIS',
  `job_fail_retry` INT DEFAULT 3 COMMENT '失败重试次数',
  `job_retry_interval` INT DEFAULT 0 COMMENT '失败重试间隔(秒)',
  `job_execute_timeout` INT DEFAULT 0 COMMENT '执行超时时间(秒)',
  `job_execute_bean` VARCHAR(255) DEFAULT NULL COMMENT '执行器处理器名称',
  `job_execute_param` VARCHAR(512) DEFAULT NULL COMMENT '执行参数',
  `job_exception_callback_bean` VARCHAR(255) DEFAULT NULL COMMENT '异常回调处理器',
  `job_retry_callback_bean` VARCHAR(255) DEFAULT NULL COMMENT '重试前回调处理器',
  `job_execute_misfire_strategy` VARCHAR(50) DEFAULT 'DO_NOTHING' COMMENT '错失策略',
  `job_trigger_last_time` BIGINT DEFAULT 0 COMMENT '上次调度时间',
  `job_trigger_next_time` BIGINT DEFAULT 0 COMMENT '下次调度时间',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`job_id`),
  UNIQUE KEY `uk_payment_sys_job_no` (`job_no`),
  KEY `idx_payment_sys_job_status` (`job_trigger_status`),
  KEY `idx_payment_sys_job_next_time` (`job_trigger_next_time`),
  KEY `idx_payment_sys_job_dispatch_mode` (`job_dispatch_mode`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='支付调度任务表';

CREATE TABLE IF NOT EXISTS `payment_sys_job_log` (
  `job_log_id` INT NOT NULL AUTO_INCREMENT COMMENT '日志ID',
  `job_log_no` VARCHAR(64) NOT NULL COMMENT '日志编号',
  `job_id` INT DEFAULT NULL COMMENT '任务ID',
  `job_no` VARCHAR(64) DEFAULT NULL COMMENT '任务编号',
  `job_log_app` VARCHAR(255) DEFAULT NULL COMMENT '触发应用',
  `job_log_trigger_bean` VARCHAR(255) DEFAULT NULL COMMENT '执行器处理器名称',
  `job_log_trigger_type` VARCHAR(50) DEFAULT NULL COMMENT '触发类型',
  `job_log_profile` VARCHAR(50) DEFAULT NULL COMMENT '环境',
  `job_log_trigger_time` DATETIME DEFAULT NULL COMMENT '触发时间',
  `job_log_trigger_date` DATE DEFAULT NULL COMMENT '触发日期',
  `job_log_trigger_code` VARCHAR(20) DEFAULT NULL COMMENT '触发状态',
  `job_log_execute_code` VARCHAR(20) DEFAULT 'PADDING' COMMENT '执行状态',
  `job_log_cost` DECIMAL(10,2) DEFAULT NULL COMMENT '执行耗时(ms)',
  `job_log_trigger_msg` TEXT DEFAULT NULL COMMENT '触发消息',
  `job_log_trigger_param` VARCHAR(512) DEFAULT NULL COMMENT '触发参数',
  `job_log_trigger_address` VARCHAR(255) DEFAULT NULL COMMENT '触发地址',
  `job_log_file_path` VARCHAR(500) DEFAULT NULL COMMENT '日志文件路径',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`job_log_id`),
  UNIQUE KEY `uk_payment_sys_job_log_no` (`job_log_no`),
  KEY `idx_payment_sys_job_log_date` (`job_log_trigger_date`),
  KEY `idx_payment_sys_job_log_bean` (`job_log_trigger_bean`),
  KEY `idx_payment_sys_job_log_job_no` (`job_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='支付调度任务日志表';

CREATE TABLE IF NOT EXISTS `payment_sys_job_log_detail` (
  `job_log_detail_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '日志详情ID',
  `job_log_id` INT DEFAULT NULL COMMENT '关联的任务日志ID',
  `job_log_no` VARCHAR(64) DEFAULT NULL COMMENT '关联的任务日志编号',
  `job_id` INT DEFAULT NULL COMMENT '任务ID',
  `job_no` VARCHAR(64) DEFAULT NULL COMMENT '任务编号',
  `job_log_detail_level` VARCHAR(20) DEFAULT 'INFO' COMMENT '日志级别',
  `job_log_detail_content` TEXT DEFAULT NULL COMMENT '日志内容',
  `job_log_detail_time` DATETIME DEFAULT NULL COMMENT '日志时间戳',
  `job_log_detail_phase` VARCHAR(50) DEFAULT NULL COMMENT '执行阶段',
  `job_log_detail_progress` INT DEFAULT NULL COMMENT '执行进度(0-100)',
  `job_log_detail_file_path` VARCHAR(500) DEFAULT NULL COMMENT '日志文件路径',
  `job_log_detail_handler` VARCHAR(255) DEFAULT NULL COMMENT '执行的方法/Handler名',
  `job_log_detail_profile` VARCHAR(100) DEFAULT NULL COMMENT '执行环境/Profile',
  `job_log_detail_address` VARCHAR(255) DEFAULT NULL COMMENT '执行地址',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`job_log_detail_id`),
  KEY `idx_payment_sys_job_detail_log` (`job_log_id`),
  KEY `idx_payment_sys_job_detail_job` (`job_id`),
  KEY `idx_payment_sys_job_detail_job_no` (`job_no`),
  KEY `idx_payment_sys_job_detail_time` (`job_log_detail_time`),
  KEY `idx_payment_sys_job_detail_level` (`job_log_detail_level`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='支付调度任务日志详情表';

CREATE TABLE IF NOT EXISTS `payment_sys_job_log_backup` (
  `job_log_backup_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '备份记录ID',
  `job_log_backup_file_name` VARCHAR(255) DEFAULT NULL COMMENT '备份文件名',
  `job_log_backup_file_path` VARCHAR(500) DEFAULT NULL COMMENT '备份文件路径',
  `job_log_backup_file_size` BIGINT DEFAULT NULL COMMENT '备份文件大小(字节)',
  `job_log_backup_count` BIGINT DEFAULT NULL COMMENT '备份日志条数',
  `job_log_backup_start_date` DATE DEFAULT NULL COMMENT '备份日志开始日期',
  `job_log_backup_end_date` DATE DEFAULT NULL COMMENT '备份日志结束日期',
  `job_log_backup_status` VARCHAR(20) DEFAULT 'RUNNING' COMMENT '备份状态',
  `job_log_backup_type` VARCHAR(20) DEFAULT 'MANUAL' COMMENT '备份类型',
  `job_log_backup_start_time` DATETIME DEFAULT NULL COMMENT '备份开始时间',
  `job_log_backup_end_time` DATETIME DEFAULT NULL COMMENT '备份完成时间',
  `job_log_backup_cost` BIGINT DEFAULT NULL COMMENT '备份耗时(毫秒)',
  `job_log_backup_message` VARCHAR(1000) DEFAULT NULL COMMENT '备份消息/错误信息',
  `job_log_backup_compress_type` VARCHAR(20) DEFAULT 'ZIP' COMMENT '压缩格式',
  `job_log_backup_cleaned` TINYINT(1) DEFAULT 0 COMMENT '是否已删除原始日志',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`job_log_backup_id`),
  KEY `idx_payment_sys_job_backup_status` (`job_log_backup_status`),
  KEY `idx_payment_sys_job_backup_type` (`job_log_backup_type`),
  KEY `idx_payment_sys_job_backup_start_time` (`job_log_backup_start_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='支付调度任务日志备份表';
