CREATE TABLE IF NOT EXISTS `payment_refund_order` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `refund_no` VARCHAR(40) NOT NULL COMMENT '退款单号',
  `order_id` BIGINT NOT NULL COMMENT '支付订单ID',
  `order_no` VARCHAR(40) NOT NULL COMMENT '支付订单号',
  `merchant_id` BIGINT NOT NULL COMMENT '商户ID',
  `channel_id` BIGINT DEFAULT NULL COMMENT '支付方式ID',
  `source_order_status` VARCHAR(32) DEFAULT NULL COMMENT '发起退款前订单状态',
  `third_party_refund_no` VARCHAR(100) DEFAULT NULL COMMENT '第三方退款单号',
  `refund_amount` DECIMAL(18,2) NOT NULL COMMENT '退款金额',
  `status` VARCHAR(32) NOT NULL DEFAULT 'PROCESSING' COMMENT '退款状态',
  `reason` VARCHAR(500) DEFAULT NULL COMMENT '退款原因',
  `notify_status` TINYINT NOT NULL DEFAULT 0 COMMENT '回调状态:0未收到 1已收到',
  `request_payload` TEXT DEFAULT NULL COMMENT '退款请求快照',
  `response_payload` TEXT DEFAULT NULL COMMENT '退款响应快照',
  `operator` VARCHAR(100) DEFAULT NULL COMMENT '操作人',
  `remark` VARCHAR(500) DEFAULT NULL COMMENT '备注',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  UNIQUE KEY `uk_payment_refund_order_refund_no` (`refund_no`),
  KEY `idx_payment_refund_order_order` (`order_id`, `created_at`),
  KEY `idx_payment_refund_order_status` (`status`, `updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='支付退款单表';

CREATE TABLE IF NOT EXISTS `payment_notify_log` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  `notify_type` VARCHAR(32) NOT NULL COMMENT '通知类型',
  `channel_id` BIGINT DEFAULT NULL COMMENT '支付方式ID',
  `channel_type` VARCHAR(32) DEFAULT NULL COMMENT '渠道类型',
  `channel_sub_type` VARCHAR(32) DEFAULT NULL COMMENT '渠道子类型',
  `request_headers` TEXT DEFAULT NULL COMMENT '请求头快照',
  `request_body` LONGTEXT DEFAULT NULL COMMENT '请求体快照',
  `sign_verified` TINYINT NOT NULL DEFAULT 0 COMMENT '验签结果:0失败 1成功',
  `process_status` VARCHAR(32) NOT NULL DEFAULT 'PROCESSING' COMMENT '处理状态',
  `process_result` VARCHAR(1000) DEFAULT NULL COMMENT '处理结果',
  `related_order_id` BIGINT DEFAULT NULL COMMENT '关联订单ID',
  `related_refund_id` BIGINT DEFAULT NULL COMMENT '关联退款单ID',
  `retry_count` INT NOT NULL DEFAULT 0 COMMENT '重试次数',
  `received_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '接收时间',
  `processed_time` DATETIME DEFAULT NULL COMMENT '处理完成时间',
  KEY `idx_payment_notify_log_type_time` (`notify_type`, `received_time`),
  KEY `idx_payment_notify_log_order` (`related_order_id`),
  KEY `idx_payment_notify_log_refund` (`related_refund_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='支付回调日志表';
