-- 钱包订单表
CREATE TABLE IF NOT EXISTS `wallet_order` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `order_no` VARCHAR(64) NOT NULL COMMENT '订单号',
    `order_type` VARCHAR(32) NOT NULL COMMENT '订单类型: RECHARGE-充值, TRANSFER-转账, WITHDRAW-提现',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID',
    `merchant_id` BIGINT NOT NULL COMMENT '商户ID',
    `user_id` BIGINT NOT NULL COMMENT '用户ID',
    `related_user_id` BIGINT NULL COMMENT '关联用户ID(转账时使用)',
    `amount` DECIMAL(15,2) NOT NULL COMMENT '金额',
    `status` VARCHAR(32) NOT NULL COMMENT '状态: PENDING-待处理, PROCESSING-处理中, SUCCESS-成功, FAILED-失败',
    `third_party_order_no` VARCHAR(128) NULL COMMENT '第三方订单号',
    `bank_account` VARCHAR(64) NULL COMMENT '银行账号',
    `bank_name` VARCHAR(128) NULL COMMENT '银行名称',
    `account_name` VARCHAR(64) NULL COMMENT '账户名',
    `request_payload` TEXT NULL COMMENT '请求报文',
    `response_payload` TEXT NULL COMMENT '响应报文',
    `operator` VARCHAR(64) NULL COMMENT '操作人',
    `remark` VARCHAR(512) NULL COMMENT '备注',
    `completed_at` DATETIME NULL COMMENT '完成时间',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_by` VARCHAR(64) NULL COMMENT '创建人',
    `update_by` VARCHAR(64) NULL COMMENT '更新人',
    `create_name` VARCHAR(64) NULL COMMENT '创建人姓名',
    `update_name` VARCHAR(64) NULL COMMENT '更新人姓名',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_order_no` (`order_no`),
    KEY `idx_tenant_merchant` (`tenant_id`, `merchant_id`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_order_type` (`order_type`),
    KEY `idx_status` (`status`),
    KEY `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='钱包订单表';

-- 商户钱包限额配置表
CREATE TABLE IF NOT EXISTS `merchant_wallet_limit` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID',
    `merchant_id` BIGINT NOT NULL COMMENT '商户ID',
    `single_recharge_limit` DECIMAL(15,2) NULL COMMENT '单笔充值限额',
    `daily_recharge_limit` DECIMAL(15,2) NULL COMMENT '日充值限额',
    `single_withdraw_limit` DECIMAL(15,2) NULL COMMENT '单笔提现限额',
    `daily_withdraw_limit` DECIMAL(15,2) NULL COMMENT '日提现限额',
    `single_transfer_limit` DECIMAL(15,2) NULL COMMENT '单笔转账限额',
    `daily_transfer_limit` DECIMAL(15,2) NULL COMMENT '日转账限额',
    `balance_limit` DECIMAL(15,2) NULL COMMENT '余额上限',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_by` VARCHAR(64) NULL COMMENT '创建人',
    `update_by` VARCHAR(64) NULL COMMENT '更新人',
    `create_name` VARCHAR(64) NULL COMMENT '创建人姓名',
    `update_name` VARCHAR(64) NULL COMMENT '更新人姓名',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_tenant_merchant` (`tenant_id`, `merchant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商户钱包限额配置表';
