-- 支付回调记录表
CREATE TABLE IF NOT EXISTS `payment_notify_log` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `notify_type` VARCHAR(32) NOT NULL COMMENT '回调类型: PAYMENT-支付回调, REFUND-退款回调',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID',
    `merchant_id` BIGINT NOT NULL COMMENT '商户ID',
    `channel_type` VARCHAR(32) NOT NULL COMMENT '渠道类型',
    `channel_sub_type` VARCHAR(32) NULL COMMENT '渠道子类型',
    `order_id` BIGINT NULL COMMENT '关联订单ID',
    `order_no` VARCHAR(64) NULL COMMENT '订单号',
    `refund_id` BIGINT NULL COMMENT '关联退款单ID',
    `refund_no` VARCHAR(64) NULL COMMENT '退款单号',
    `third_party_trade_no` VARCHAR(128) NULL COMMENT '第三方交易号',
    `request_headers` TEXT NULL COMMENT '请求头',
    `request_body` TEXT NULL COMMENT '请求体',
    `request_params` TEXT NULL COMMENT '请求参数',
    `sign_verified` TINYINT(1) NULL COMMENT '签名验证结果: 0-失败, 1-成功',
    `process_status` VARCHAR(32) NOT NULL COMMENT '处理状态: PENDING-待处理, PROCESSING-处理中, SUCCESS-成功, FAILED-失败',
    `process_result` TEXT NULL COMMENT '处理结果',
    `error_message` VARCHAR(512) NULL COMMENT '错误信息',
    `retry_count` INT NOT NULL DEFAULT 0 COMMENT '重试次数',
    `received_at` DATETIME NOT NULL COMMENT '接收时间',
    `processed_at` DATETIME NULL COMMENT '处理时间',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_tenant_merchant` (`tenant_id`, `merchant_id`),
    KEY `idx_order_no` (`order_no`),
    KEY `idx_refund_no` (`refund_no`),
    KEY `idx_process_status` (`process_status`),
    KEY `idx_received_at` (`received_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='支付回调记录表';

-- 回调异常记录表
CREATE TABLE IF NOT EXISTS `payment_notify_error` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `notify_log_id` BIGINT NOT NULL COMMENT '回调记录ID',
    `notify_type` VARCHAR(32) NOT NULL COMMENT '回调类型',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID',
    `merchant_id` BIGINT NOT NULL COMMENT '商户ID',
    `order_no` VARCHAR(64) NULL COMMENT '订单号',
    `refund_no` VARCHAR(64) NULL COMMENT '退款单号',
    `error_type` VARCHAR(64) NOT NULL COMMENT '错误类型',
    `error_message` TEXT NULL COMMENT '错误信息',
    `error_stack` TEXT NULL COMMENT '错误堆栈',
    `request_data` TEXT NULL COMMENT '请求数据',
    `retry_count` INT NOT NULL DEFAULT 0 COMMENT '重试次数',
    `max_retry_count` INT NOT NULL DEFAULT 5 COMMENT '最大重试次数',
    `next_retry_time` DATETIME NULL COMMENT '下次重试时间',
    `status` VARCHAR(32) NOT NULL COMMENT '状态: PENDING-待处理, PROCESSING-处理中, RESOLVED-已解决, ABANDONED-已放弃',
    `resolved_at` DATETIME NULL COMMENT '解决时间',
    `resolved_by` VARCHAR(64) NULL COMMENT '解决人',
    `remark` VARCHAR(512) NULL COMMENT '备注',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`),
    KEY `idx_notify_log_id` (`notify_log_id`),
    KEY `idx_status` (`status`),
    KEY `idx_next_retry_time` (`next_retry_time`),
    KEY `idx_tenant_merchant` (`tenant_id`, `merchant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='回调异常记录表';

-- 商户支付配置表
CREATE TABLE IF NOT EXISTS `merchant_payment_config` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `tenant_id` BIGINT NOT NULL COMMENT '租户ID',
    `merchant_id` BIGINT NOT NULL COMMENT '商户ID',
    `order_reusable` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '订单是否可重复支付: 0-一次性订单, 1-可重复支付',
    `order_timeout_minutes` INT NULL COMMENT '订单超时时间(分钟), NULL表示不超时',
    `pending_order_limit` INT NULL COMMENT '待支付订单数量限制: NULL-不限制, 1-只能有一个待支付订单',
    `auto_cancel_timeout_order` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否自动取消超时订单',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `create_by` VARCHAR(64) NULL COMMENT '创建人',
    `update_by` VARCHAR(64) NULL COMMENT '更新人',
    `create_name` VARCHAR(64) NULL COMMENT '创建人姓名',
    `update_name` VARCHAR(64) NULL COMMENT '更新人姓名',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_tenant_merchant` (`tenant_id`, `merchant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='商户支付配置表';
